


import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '../../components/navbar/NavBar'
import Cataloge from '../../components/cataloge/Cataloge'
import Hero from '../../components/hero/Hero'

import Footer from '../../components/footer/Footer'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home({meals}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <Hero />
        <Cataloge meals={meals} />
        <Footer />
      </div>
    </>
  )
}


export async function getServerSideProps(){
 
  const{data}=await axios.get("http://localhost:3000/api/meal",{next:{revalidate:10}})
 
  return{
    props:{
      meals:data
    }}
  }